/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnCvSampleCvRouteImport } from './routes/en/cv/sampleCv'

const EnCvSampleCvRoute = EnCvSampleCvRouteImport.update({
  id: '/en/cv/sampleCv',
  path: '/en/cv/sampleCv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRoutesByTo {
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/en/cv/sampleCv'
  fileRoutesByTo: FileRoutesByTo
  to: '/en/cv/sampleCv'
  id: '__root__' | '/en/cv/sampleCv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EnCvSampleCvRoute: typeof EnCvSampleCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/en/cv/sampleCv': {
      id: '/en/cv/sampleCv'
      path: '/en/cv/sampleCv'
      fullPath: '/en/cv/sampleCv'
      preLoaderRoute: typeof EnCvSampleCvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EnCvSampleCvRoute: EnCvSampleCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
