/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnProfileRouteImport } from './routes/en/profile'
import { Route as EnHomeRouteImport } from './routes/en/home'
import { Route as EnCvSampleCvRouteImport } from './routes/en/cv/sampleCv'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProfileRoute = EnProfileRouteImport.update({
  id: '/en/profile',
  path: '/en/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHomeRoute = EnHomeRouteImport.update({
  id: '/en/home',
  path: '/en/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCvSampleCvRoute = EnCvSampleCvRouteImport.update({
  id: '/en/cv/sampleCv',
  path: '/en/cv/sampleCv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/en/home': typeof EnHomeRoute
  '/en/profile': typeof EnProfileRoute
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/en/home': typeof EnHomeRoute
  '/en/profile': typeof EnProfileRoute
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/en/home': typeof EnHomeRoute
  '/en/profile': typeof EnProfileRoute
  '/en/cv/sampleCv': typeof EnCvSampleCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/en/home' | '/en/profile' | '/en/cv/sampleCv'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/en/home' | '/en/profile' | '/en/cv/sampleCv'
  id: '__root__' | '/login' | '/en/home' | '/en/profile' | '/en/cv/sampleCv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  EnHomeRoute: typeof EnHomeRoute
  EnProfileRoute: typeof EnProfileRoute
  EnCvSampleCvRoute: typeof EnCvSampleCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/profile': {
      id: '/en/profile'
      path: '/en/profile'
      fullPath: '/en/profile'
      preLoaderRoute: typeof EnProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/home': {
      id: '/en/home'
      path: '/en/home'
      fullPath: '/en/home'
      preLoaderRoute: typeof EnHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/cv/sampleCv': {
      id: '/en/cv/sampleCv'
      path: '/en/cv/sampleCv'
      fullPath: '/en/cv/sampleCv'
      preLoaderRoute: typeof EnCvSampleCvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  EnHomeRoute: EnHomeRoute,
  EnProfileRoute: EnProfileRoute,
  EnCvSampleCvRoute: EnCvSampleCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
